Resources:
  EventDynamoDbTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        -
          AttributeName: eventId
          AttributeType: N
        -
          AttributeName: finish
          AttributeType: N
        -
          AttributeName: start
          AttributeType: N
      KeySchema:
        -
          AttributeName: eventId
          KeyType: HASH
      GlobalSecondaryIndexes:
        -
          IndexName: finish-start-index
          KeySchema:
            -
              AttributeName: finish
              KeyType: HASH
            -
              AttributeName: start
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: ${self:custom.eventTable.${self:provider.stage}}