Resources:
  EventDynamoDbTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: dev-event
      AttributeDefinitions:
        -
          AttributeName: eventId
          AttributeType: N
        -
          AttributeName: start
          AttributeType: N
        -
          AttributeName: countOfLike
          AttributeType: N
        -
          AttributeName: updateTime
          AttributeType: N
        -
          AttributeName: status
          AttributeType: S

      KeySchema:
        -
          AttributeName: eventId
          KeyType: HASH

      GlobalSecondaryIndexes:
        -
          IndexName: status-start-index
          KeySchema:
            -
              AttributeName: status
              KeyType: HASH
            -
              AttributeName: start
              KeyType: RANGE

          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - eventId
              - eventName
              - updateTime
              - end
              - location
              - urlData
              - countOfLike
              - university

        -
          IndexName: status-countOfLike-index
          KeySchema:
            -
              AttributeName: status
              KeyType: HASH
            -
              AttributeName: countOfLike
              KeyType: RANGE

          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - eventId
              - eventName
              - updateTime
              - end
              - location
              - urlData
              - start
              - university

        -
          IndexName: status-updateTime-index
          KeySchema:
            -
              AttributeName: status
              KeyType: HASH
            -
              AttributeName: updateTime
              KeyType: RANGE

          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - eventId
              - eventName
              - countOfLike
              - end
              - location
              - urlData
              - start
              - university