Resources:
  SequenceDynamoDbTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: dev-sequence
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: tableName
          AttributeType: S
      KeySchema:
        -
          AttributeName: tableName
          KeyType: HASH