#s3の画像ファイルのARN
ARN_S3: "https://s3-ap-northeast-1.amazonaws.com"

#dynamodbのテーブル名
PROFILE_TABLE: ${self:custom.profileTable.${self:provider.stage}}
EVENT_TABLE: ${self:custom.eventTable.${self:provider.stage}}
SEQUENCE_TABLE: ${self:custom.sequenceTable.${self:provider.stage}}

#プロフィールテーブルのインデックス
PROFILE_CHECK_SODA_ID_INDEX: check-sodaId-index
PROFILE_CHECK_Email_INDEX: check-email-index
PROFILE_SODA_ID_INDEX: sodaId-index

#イベントテーブルのインデックス
EVENT_STATUS_START_INDEX: status-start-index
EVENT_STATUS_COUNTOFLIKE_INDEX: status-countOfLike-index
EVENT_STATUS_UPDATETIME_INDEX: status-updateTime-index

#S3のバケット名
S3_JSON_BUCKET: soda-json
S3_IMAGE_BUCKET: ${self:custom.imageBucket.${self:provider.stage}}

#S3のファイル名
FAQS_JSON: faqs.json
TERMS_JSON: terms.json
UNIVERSITY_JSON: university.json

SNS_CANCEL_TOPIC: arn:aws:sns:ap-northeast-1:004586830768:${self:custom.sns.cancelTopic.${self:provider.stage}}
SNS_SEND_WEEK_MAIL: arn:aws:sns:ap-northeast-1:004586830768:${self:custom.sns.sendWeekMail.${self:provider.stage}}

SES_REGION: us-east-1

#メールを送信する際の差出人のメールアドレス
MAIL_ADRESS_FROM_SODA: Soda <info@sodaevent.com>

#お問い合わせからのメールを受け取る際のアドレス
MAIL_ADRESS_CONTACT: shunsuke.kmkz0617@gmail.com

TWITTER_CONSUMER_KEY: h7KEh32IEQEEFWYE5jKTIzEom
TWITTER_CONSUMER_SECRET: xfhLFhVFkRCBRrfZUuCh6umV9Upzo5n3sRGfnT57YZQou6Zeev
ACCESS_TOKEN: 994936051050270720-5IZ9RwgAqBmamoVll3xheVMTaEkQeL8
ACCESS_SECRET: KB2LnnpH4PogBg9xE0JcVSvsaLsYxYRes64sY7SH5ZZlq

#SlackのWebhook URL
SLACK_WEB_HOOK_URL: https://hooks.slack.com/services/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